name: Build and Deploy PHP App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_to_production:
        description: 'Deploy to Production? (true/false)'
        required: false
        default: 'false'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Login to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: b04abe34-d3e1-4a15-9960-00bf52c3d692
          tenant-id: 7cb9246c-9ffa-4869-960b-f0e8772aef84
          subscription-id: 45fdcc40-c3eb-4c95-abb1-6f7ce0145829

      - name: Deploy to UAT slot
        if: github.event_name == 'push'
        run: |
          az webapp deploy --resource-group php-app --name php-webapp-prod --slot uat --src-path .

      - name: Deploy to Production slot
        if: github.event_name == 'workflow_dispatch' && inputs.deploy_to_production == 'true'
        run: |
          az webapp deploy --resource-group php-app --name php-webapp-prod --slot production --src-path .
